"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.0.6.

Production-ready for Hostinger VPS, Render, Docker, and local development
via environment variables.
"""

import os
from pathlib import Path

from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Load .env for local development and Hostinger VPS (no-op if file is absent)
load_dotenv(BASE_DIR / ".env")

# Hostinger / generic MySQL (MariaDB) without compiling mysqlclient.
try:
    import pymysql

    pymysql.install_as_MySQLdb()
except ImportError:
    pass


def _csv_env(name, default=""):
    return [item.strip() for item in os.environ.get(name, default).split(",") if item.strip()]


def _hostname(value):
    """Strip scheme, path, and port from a domain or URL."""
    if not value:
        return ""
    host = value.strip()
    host = host.replace("https://", "").replace("http://", "")
    return host.split("/")[0].split(":")[0].strip()


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get(
    "SECRET_KEY",
    "django-insecure-+dxv3hg%z8=xn%2x=6ol3jw6%p-s7b#+s^3c!)23s5vmvbuz-5",
)

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get("DEBUG", "True").lower() in ("1", "true", "yes", "on")

if not DEBUG and (
    not SECRET_KEY
    or SECRET_KEY.startswith("django-insecure-")
    or SECRET_KEY in ("your-secret-key-change-this-in-production", "changeme")
):
    from django.core.exceptions import ImproperlyConfigured

    raise ImproperlyConfigured(
        "Set a strong SECRET_KEY in the environment (or .env) before running "
        "with DEBUG=False."
    )

# Render sets RENDER=true; Hostinger uses SITE_DOMAIN / VPS_IP / ALLOWED_HOSTS.
# In production without an explicit ALLOWED_HOSTS, still allow local probes
# so collectstatic/migrate/health tooling does not break during builds.
_default_hosts = "127.0.0.1,localhost"
ALLOWED_HOSTS = _csv_env("ALLOWED_HOSTS", _default_hosts)
if os.environ.get("RENDER") or os.environ.get("RENDER_EXTERNAL_HOSTNAME"):
    if ".onrender.com" not in ALLOWED_HOSTS:
        ALLOWED_HOSTS.append(".onrender.com")
    render_host = os.environ.get("RENDER_EXTERNAL_HOSTNAME")
    if render_host and render_host not in ALLOWED_HOSTS:
        ALLOWED_HOSTS.append(render_host)

_site_domain = _hostname(os.environ.get("SITE_DOMAIN", ""))
if _site_domain:
    if _site_domain not in ALLOWED_HOSTS:
        ALLOWED_HOSTS.append(_site_domain)
    if _site_domain.startswith("www."):
        bare = _site_domain[4:]
        if bare and bare not in ALLOWED_HOSTS:
            ALLOWED_HOSTS.append(bare)
    elif f"www.{_site_domain}" not in ALLOWED_HOSTS:
        ALLOWED_HOSTS.append(f"www.{_site_domain}")

_vps_ip = _hostname(os.environ.get("VPS_IP", ""))
if _vps_ip and _vps_ip not in ALLOWED_HOSTS:
    ALLOWED_HOSTS.append(_vps_ip)

# Allow "*" only when explicitly requested (never default).
if os.environ.get("ALLOWED_HOSTS", "").strip() == "*":
    ALLOWED_HOSTS = ["*"]

# CSRF trusted origins (required for HTTPS forms behind Hostinger / Render proxies)
CSRF_TRUSTED_ORIGINS = _csv_env("CSRF_TRUSTED_ORIGINS")
_render_hostname = os.environ.get("RENDER_EXTERNAL_HOSTNAME")
if _render_hostname:
    _origin = f"https://{_render_hostname}"
    if _origin not in CSRF_TRUSTED_ORIGINS:
        CSRF_TRUSTED_ORIGINS.append(_origin)

for host in ALLOWED_HOSTS:
    if host in ("*", "localhost", "127.0.0.1") or host.startswith("."):
        continue
    for scheme in ("https", "http"):
        origin = f"{scheme}://{host}"
        if origin not in CSRF_TRUSTED_ORIGINS:
            CSRF_TRUSTED_ORIGINS.append(origin)


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "rest_framework",
    "corsheaders",
    "courses",
    "api",
    "admin_panel",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "corsheaders.middleware.CorsMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    "courses.middleware.InlineMediaMiddleware",
]

ROOT_URLCONF = "config.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / "templates"],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
                "courses.context_processors.user_roles",
            ],
        },
    },
]

WSGI_APPLICATION = "config.wsgi.application"


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases
# Prefer DATABASE_URL (Render / Hostinger Postgres); then discrete DATABASE_*
# env vars (Postgres or MySQL/MariaDB); fall back to local SQLite.


def _build_databases():
    database_url = os.environ.get("DATABASE_URL")
    if database_url:
        try:
            import dj_database_url

            # Render Postgres requires SSL; Hostinger local MySQL/Postgres does not.
            ssl_require = bool(os.environ.get("RENDER")) or os.environ.get(
                "DATABASE_SSL_REQUIRE", ""
            ).lower() in ("1", "true", "yes", "on")
            return {
                "default": dj_database_url.config(
                    default=database_url,
                    conn_max_age=600,
                    conn_health_checks=True,
                    ssl_require=ssl_require,
                )
            }
        except Exception:
            pass

    engine = os.environ.get("DATABASE_ENGINE", "").strip()
    if engine and ("postgresql" in engine or "postgres" in engine):
        return {
            "default": {
                "ENGINE": "django.db.backends.postgresql",
                "NAME": os.environ.get("DATABASE_NAME", "learning_hub"),
                "USER": os.environ.get("DATABASE_USER", "postgres"),
                "PASSWORD": os.environ.get("DATABASE_PASSWORD", "postgres"),
                "HOST": os.environ.get("DATABASE_HOST", "localhost"),
                "PORT": os.environ.get("DATABASE_PORT", "5432"),
            }
        }

    if engine and "mysql" in engine:
        return {
            "default": {
                "ENGINE": "django.db.backends.mysql",
                "NAME": os.environ.get("DATABASE_NAME", "studynation"),
                "USER": os.environ.get("DATABASE_USER", "studynation"),
                "PASSWORD": os.environ.get("DATABASE_PASSWORD", ""),
                "HOST": os.environ.get("DATABASE_HOST", "localhost"),
                "PORT": os.environ.get("DATABASE_PORT", "3306"),
                "OPTIONS": {
                    "charset": "utf8mb4",
                    "init_command": "SET sql_mode='STRICT_TRANS_TABLES'",
                },
            }
        }

    return {
        "default": {
            "ENGINE": "django.db.backends.sqlite3",
            "NAME": BASE_DIR / "db.sqlite3",
        }
    }


DATABASES = _build_databases()

# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = "/static/"
STATIC_ROOT = Path(os.environ.get("STATIC_ROOT", BASE_DIR / "staticfiles"))
STATICFILES_DIRS = [BASE_DIR / "static"] if (BASE_DIR / "static").exists() else []

# WhiteNoise compressed static files (Manifest optional; CompressedStaticFilesStorage
# avoids hard failures if a referenced file is missing during collectstatic)
STORAGES = {
    "default": {
        "BACKEND": "django.core.files.storage.FileSystemStorage",
    },
    "staticfiles": {
        "BACKEND": "whitenoise.storage.CompressedStaticFilesStorage",
    },
}

MEDIA_URL = "/media/"
MEDIA_ROOT = Path(os.environ.get("MEDIA_ROOT", BASE_DIR / "media"))

# Question import preview can post many fields (one bank of 80+ questions
# with options/metadata). Django's default 1000 limit raises TooManyFieldsSent.
# The preview form also sends a single JSON payload; this is a safety net.
DATA_UPLOAD_MAX_NUMBER_FIELDS = int(
    os.environ.get("DATA_UPLOAD_MAX_NUMBER_FIELDS", "20000")
)
# Blog video/PDF/PPT uploads + Word/equation payloads. Default 100MB so
# multi-file blog posts (image + video + PDF + PPT) are not rejected with
# RequestDataTooBig before the form can validate individual field limits.
DATA_UPLOAD_MAX_MEMORY_SIZE = int(
    os.environ.get("DATA_UPLOAD_MAX_MEMORY_SIZE", str(100 * 1024 * 1024))
)
# Keep modest in-memory buffering; larger files spill to temp disk.
FILE_UPLOAD_MAX_MEMORY_SIZE = int(
    os.environ.get("FILE_UPLOAD_MAX_MEMORY_SIZE", str(10 * 1024 * 1024))
)

# CORS Configuration — open in local DEBUG, locked down in production
_cors_default = "True" if DEBUG else "False"
CORS_ALLOW_ALL_ORIGINS = os.environ.get(
    "CORS_ALLOW_ALL_ORIGINS", _cors_default
).lower() in ("1", "true", "yes", "on")

# REST Framework Configuration
REST_FRAMEWORK = {
    "DEFAULT_PAGINATION_CLASS": "rest_framework.pagination.PageNumberPagination",
    "PAGE_SIZE": 20,
}

# Default auto field
DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# ---------------------------------------------------------------------------
# Production / reverse-proxy security (Hostinger OpenLiteSpeed or Nginx,
# Render). Only applied when DEBUG is False.
# ---------------------------------------------------------------------------
# TLS is terminated at Nginx / OpenLiteSpeed / Render; trust forwarded proto.
SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")
USE_X_FORWARDED_HOST = os.environ.get("USE_X_FORWARDED_HOST", "True").lower() in (
    "1",
    "true",
    "yes",
    "on",
)
USE_X_FORWARDED_PORT = True

if not DEBUG:
    # Default SSL redirect ON once HTTPS is live. Set SECURE_SSL_REDIRECT=False
    # for the first Hostinger deploy before Let's Encrypt is issued.
    SECURE_SSL_REDIRECT = os.environ.get("SECURE_SSL_REDIRECT", "True").lower() in (
        "1",
        "true",
        "yes",
        "on",
    )
    SECURE_REDIRECT_EXEMPT = [r"^healthz/?$"]
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    SECURE_BROWSER_XSS_FILTER = True
    SECURE_CONTENT_TYPE_NOSNIFF = True
    # SAMEORIGIN (not DENY): past papers / resource viewers embed PDFs from
    # the same host; DENY can cause blank viewers and odd client errors.
    X_FRAME_OPTIONS = os.environ.get("X_FRAME_OPTIONS", "SAMEORIGIN")
    # HSTS: enable after you confirm HTTPS works end-to-end
    SECURE_HSTS_SECONDS = int(os.environ.get("SECURE_HSTS_SECONDS", "31536000"))
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True

# Logging — console logging for Hostinger journalctl / Render log stream
LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "formatters": {
        "verbose": {
            "format": "[{asctime}] {levelname} {name}: {message}",
            "style": "{",
        },
    },
    "handlers": {
        "console": {
            "class": "logging.StreamHandler",
            "formatter": "verbose",
        },
    },
    "root": {
        "handlers": ["console"],
        "level": os.environ.get("LOG_LEVEL", "INFO"),
    },
    "loggers": {
        "django.request": {
            "handlers": ["console"],
            "level": "WARNING",
            "propagate": False,
        },
        "courses": {
            "handlers": ["console"],
            "level": "INFO",
            "propagate": False,
        },
        "admin_panel": {
            "handlers": ["console"],
            "level": "INFO",
            "propagate": False,
        },
    },
}
